import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Eye, LockKeyhole, ShieldCheck, Users } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import LivingSecurePayMark from '../components/LivingSecurePayMark';
import SecurePayLogo from '../components/SecurePayLogo';
import { useAuth } from '../lib/auth';
import { loadCreationIntent, type CreationIntent } from '../lib/creationIntent';
import { buildAgreementBlueprint, parseKenyanAmountMinor } from '../lib/agreementIntelligence';
import { confirmAgreementVersion, createAgreement, createGroupSecureLink, issueGroupSecureLinkPublicLocator, listAgreementVersions } from '../api/securepayEndpoints';

type Step = 'you' | 'situation' | 'purpose' | 'settings' | 'beneficiary' | 'governance' | 'review';
const STEPS: Array<{ id: Step; label: string }> = [
  { id: 'you', label: 'You' }, { id: 'situation', label: 'Situation' }, { id: 'purpose', label: 'Purpose & amount' }, { id: 'settings', label: 'How it runs' }, { id: 'beneficiary', label: 'Who it’s for' }, { id: 'governance', label: 'How the group agrees' }, { id: 'review', label: 'Review' },
];

const DEFAULT_INTENT: CreationIntent = { id:'collect', family:'life', statement:'We are contributing together for a shared purpose.', who:'Contributors to be confirmed → Recipient or purpose to be confirmed', what:'Group contribution', amount:'To be confirmed', mustHappen:'The purpose, contributors and recipient are agreed before the collection is used.', nextStep:'Confirm who is contributing, who receives and how the contribution should work.', nextStepShort:'Shape the group agreement', moneyMoves:'Only according to the contribution arrangement the participants agree.' };

function InlineCollectAuth({ onDone }: { onDone: () => void }) {
  const { signIn, completeSignIn, challenge } = useAuth();
  const [ks, setKs] = useState(''); const [password, setPassword] = useState(''); const [otp, setOtp] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async () => { setBusy(true); setError(''); const result = challenge ? await completeSignIn(otp.trim()) : await signIn(ks.trim(), password); setBusy(false); if (result) setError(result); else if (challenge) onDone(); };
  return <div className="collect-auth"><LivingSecurePayMark state="guiding" size="md" presence="present"/><h2>{challenge ? 'Enter your code' : 'Sign in to create the Group SecureLink'}</h2><p>Your answers stay here. Sign-in only establishes who is creating the agreement.</p>{error && <div className="collect-error">{error}</div>}{challenge ? <input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Verification code"/> : <><input value={ks} onChange={e=>setKs(e.target.value.toUpperCase())} placeholder="KSNumber"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password"/></>}<button type="button" onClick={() => void submit()} disabled={busy}>{busy ? 'Please wait…' : 'Continue'} <ArrowRight size={16}/></button></div>;
}

export default function CollectJourney({ previewMode = false }: { previewMode?: boolean }) {
  const location = useLocation(); const navigate = useNavigate(); const { session } = useAuth();
  const initial = (location.state as { intent?: CreationIntent } | null)?.intent ?? loadCreationIntent() ?? DEFAULT_INTENT;
  const blueprint = useMemo(() => buildAgreementBlueprint(initial), [initial]);
  const [step, setStep] = useState<Step>('you'); const [organiserName, setOrganiserName] = useState(''); const [groupType, setGroupType] = useState(initial.family === 'life' ? 'WELFARE' : 'GENERAL'); const [purpose, setPurpose] = useState(initial.statement); const [amount, setAmount] = useState(blueprint.amountText || initial.amount.replace(/^To be confirmed$/,'') || ''); const [frequency, setFrequency] = useState('one-time'); const [deadline, setDeadline] = useState(''); const [beneficiary, setBeneficiary] = useState(''); const [governance, setGovernance] = useState('organiser'); const [builderKs, setBuilderKs] = useState(''); const [authGate, setAuthGate] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const index = STEPS.findIndex(s => s.id === step); const amountMinor = parseKenyanAmountMinor(amount); const mood = /wedding|harusi|bride|groom/i.test(purpose) ? 'wedding' : /school|fees|student/i.test(purpose) ? 'school' : /medical|hospital|treatment/i.test(purpose) ? 'medical' : /funeral|burial|bereavement/i.test(purpose) ? 'funeral' : /church|welfare|family|support/i.test(purpose) ? 'support' : 'general';
  const next = () => { if (index < STEPS.length - 1) setStep(STEPS[index + 1].id); }; const back = () => { if (index > 0) setStep(STEPS[index - 1].id); else navigate(previewMode ? '/preview/home' : '/'); };
  const ready = purpose.trim().length > 8 && Boolean(amountMinor) && beneficiary.trim().length > 1;
  const submit = async () => {
    if (!ready || busy) return; if (previewMode) { navigate('/preview/workspace'); return; } if (!session?.accessToken) { setAuthGate(true); return; }
    setBusy(true); setError(''); try {
      const created = await createAgreement({ idempotencyKey: crypto.randomUUID(), agreementType:'GENERIC', title: purpose.slice(0,72), purpose, description:[`Group SecureLink`, `Organiser: ${organiserName || 'Signed-in creator'}`, `Beneficiary: ${beneficiary}`, `Run: ${frequency}${deadline ? ` until ${deadline}` : ''}`, `Governance preference: ${governance === 'committee' ? 'Committee approval' : 'Lead organiser'}`, builderKs.trim() ? `Builder / referrer KSNumber: ${builderKs.trim().toUpperCase()}` : ''].filter(Boolean).join('\n'), currency:'KES', proposedAmountMinor: amountMinor!, saveAsDraft:false }, session.accessToken);
      if (!created.ok || !created.data) throw new Error(created.error || 'Agreement creation failed.');
      const versions = await listAgreementVersions(created.data.id, session.accessToken); const current = versions.ok && versions.data ? versions.data.find(v => v.versionStatus === 'CURRENT') ?? versions.data[0] : null; if (current) await confirmAgreementVersion(created.data.id, current.id, { idempotencyKey:crypto.randomUUID(), expectedVersionNumber:current.versionNumber, expectedContentHash:current.contentHash }, session.accessToken);
      const group = await createGroupSecureLink(created.data.id, { groupType: groupType as 'WELFARE'|'GENERAL', title: purpose.slice(0,72), statedPurpose: purpose, targetType:'FIXED_AMOUNT', targetAmountMinor: amountMinor! }, session.accessToken); if (!group.ok || !group.data) throw new Error(group.error || 'Group SecureLink creation failed.');
      const locator = await issueGroupSecureLinkPublicLocator(created.data.id, { idempotencyKey:crypto.randomUUID() }, session.accessToken); if (!locator.ok || !locator.data) throw new Error(locator.error || 'Public link creation failed.');
      navigate(`/group/${locator.data.slug}`, { replace:true, state:{ justCreated:true, agreementId:created.data.id } });
    } catch (e) { setError(e instanceof Error ? e.message : 'SecurePay could not finish creating this Group SecureLink.'); } finally { setBusy(false); }
  };

  if (authGate) return <div className="collect-page"><header className="collect-header"><Link to="/"><SecurePayLogo size="header"/></Link></header><main className="collect-auth-wrap"><InlineCollectAuth onDone={() => setAuthGate(false)} /></main></div>;

  return <div className={`collect-page collect-mood-${mood}`}>
    <header className="collect-header"><Link to={previewMode ? '/preview/home' : '/'}><SecurePayLogo size="header" /></Link><div className="collect-progress-copy">Step {index+1} of {STEPS.length}</div></header>
    <div className="collect-progress">{STEPS.map((s,i)=><button type="button" key={s.id} onClick={()=>i<=index&&setStep(s.id)} className={i<=index?'is-on':''}><span>{i+1}</span><b>{s.label}</b></button>)}</div>
    <main className="collect-layout">
      <section className="collect-builder">
        <p className="collect-kicker">Group SecureLink</p>
        {step==='you'&&<><h1>Who is organising this?</h1><p className="collect-hint">The signed-in KSNumber remains the backend identity. This name is only how the group will recognise the organiser in the agreement.</p><label>Your name or group role<input value={organiserName} onChange={e=>setOrganiserName(e.target.value)} placeholder="e.g. Wanjiku — family organiser"/></label></>}
        {step==='situation'&&<><h1>What kind of situation is this?</h1><p className="collect-hint">SecurePay adapts the tone to the human situation without changing financial truth.</p><div className="collect-choice-grid"><button type="button" className={groupType==='GENERAL'?'is-selected':''} onClick={()=>setGroupType('GENERAL')}><span>Trade / general</span><small>Estate, project, business or other shared purpose</small></button><button type="button" className={groupType==='WELFARE'?'is-selected':''} onClick={()=>setGroupType('WELFARE')}><span>Life & support</span><small>Family, school, wedding, funeral, welfare or care</small></button></div></>}
        {step==='purpose'&&<><h1>What are people contributing towards?</h1><p className="collect-hint">Use ordinary words. The agreement should make the purpose and target clear before anyone contributes.</p><label>Purpose<textarea rows={4} value={purpose} onChange={e=>setPurpose(e.target.value)} /></label><label>Target amount<input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="e.g. KES 120,000"/></label></>}
        {step==='settings'&&<><h1>How should this run?</h1><div className="collect-choice-grid"><button type="button" className={frequency==='one-time'?'is-selected':''} onClick={()=>setFrequency('one-time')}><span>One-time collection</span><small>One purpose, one contribution cycle</small></button><button type="button" className={frequency==='recurring'?'is-selected':''} onClick={()=>setFrequency('recurring')}><span>Recurring support</span><small>Repeat according to the agreement</small></button></div><label>Deadline, if there is one<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} /></label></>}
        {step==='beneficiary'&&<><h1>Who or what is this for?</h1><p className="collect-hint">Name the intended recipient or purpose clearly. SecurePay does not infer beneficiary authority from this field.</p><label>Beneficiary / recipient<input value={beneficiary} onChange={e=>setBeneficiary(e.target.value)} placeholder="e.g. Wanjiru's wedding fund"/></label></>}
        {step==='governance'&&<><h1>How should the group agree?</h1><p className="collect-hint">This records the intended agreement structure. Actual organiser and governance authority remain backend-authoritative.</p><div className="collect-choice-grid"><button type="button" className={governance==='organiser'?'is-selected':''} onClick={()=>setGovernance('organiser')}><span>Lead organiser</span><small>One organiser coordinates the agreed actions</small></button><button type="button" className={governance==='committee'?'is-selected':''} onClick={()=>setGovernance('committee')}><span>Committee approval</span><small>Use a multi-person agreement where backend governance supports it</small></button></div></>}
        {step==='review'&&<><h1>Review the Group SecureLink.</h1><p className="collect-hint">This is the agreement before the public contribution link is issued. Creating it does not mean money has been funded or released.</p><div className="collect-review"><div><span>Purpose</span><b>{purpose}</b></div><div><span>Target</span><b>{amount || 'To confirm'}</b></div><div><span>Beneficiary</span><b>{beneficiary || 'To confirm'}</b></div><div><span>Runs</span><b>{frequency}{deadline ? ` · until ${deadline}` : ''}</b></div><div><span>Governance intention</span><b>{governance==='committee'?'Committee approval':'Lead organiser'}</b></div></div><label>Who helped bring this agreement?<input value={builderKs} onChange={e=>setBuilderKs(e.target.value.toUpperCase())} placeholder="Builder / referrer KSNumber (optional)"/></label>{error&&<div className="collect-error">{error}</div>}</>}
        <div className="collect-nav"><button type="button" className="collect-back" onClick={back}><ArrowLeft size={16}/> Back</button>{step==='review'?<button type="button" className="collect-next" disabled={!ready||busy} onClick={()=>void submit()}>{busy?'Creating…':'Create Group SecureLink'} {!busy&&<ArrowRight size={16}/>}</button>:<button type="button" className="collect-next" onClick={next}>Continue <ArrowRight size={16}/></button>}</div>
      </section>
      <aside className="collect-preview"><div className="collect-preview-head"><div><span><i/>Agreement taking shape</span><small>Live preview</small></div><LivingSecurePayMark state="guiding" size="sm" presence="present"/></div><blockquote>“{purpose}”</blockquote><h2>{purpose.slice(0,54) || 'Your group purpose'}</h2><dl><div><dt><Users size={16}/>Organiser</dt><dd>{organiserName || 'Signed-in creator'}</dd></div><div><dt><Eye size={16}/>Type</dt><dd>{groupType==='WELFARE'?'Life & support':'General group'}</dd></div><div><dt><LockKeyhole size={16}/>Target</dt><dd>{amount || 'To confirm'}</dd></div><div><dt><ShieldCheck size={16}/>Beneficiary</dt><dd>{beneficiary || 'To confirm'}</dd></div><div><dt><Check size={16}/>How it runs</dt><dd>{frequency}{deadline?` · until ${deadline}`:''}</dd></div></dl><div className="collect-truth"><b>Money should follow the agreement.</b><span>Preview only. Funding, approvals, release and settlement remain backend truth.</span></div></aside>
    </main>
  </div>;
}
